# Default values for scylladb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: scylladb/scylla
  tag: 2.3.0
  pullPolicy: IfNotPresent

service:
  nodeport:
    enabled: false
  cqlPort: 9042
  internodePort: 7000
  sslinternodePort: 7001
  jmxPort: 7199
  restPort: 10000
  prometheusPort: 9180
  nodeExporterPort: 9100
  thriftPort: 9160
  # Check http://docs.scylladb.com/admin/

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # Please check https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/#cpu-management-policies
  limits:
    cpu: 3
    memory: 10Gi

command:
  gcpGetPublicIP: '$(curl -s -X GET -H "Metadata-Flavor: Google" http://metadata/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip)'
nodeSelector: {}

tolerations: []

affinity: {}

environment:
  type: "GKE"
  public_access: true

persistence:
  accessMode: ReadWriteOnce
  size: 50Gi

config:
  cluster_name: 'K8s Cluster'
  endpoint_snitch: SimpleSnitch
  num_tokens: 256
  read_request_timeout_in_ms: 5000
  write_request_timeout_in_ms: 2000
  auto_bootstrap: false
