apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "scylladb.fullname" . }}
  labels:
    app: {{ template "scylladb.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "scylladb.name" . }}
  serviceName: {{ template "scylladb.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "scylladb.name" . }}
        release: {{ .Release.Name }}
    spec:
#      hostNetwork: true
      terminationGracePeriodSeconds: 120
      containers:
      - name: {{ template "scylladb.fullname" . }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        resources: 
{{ toYaml .Values.resources | indent 10 }}
        ports:
          - containerPort: {{ .Values.service.cqlPort }}
            hostPort: {{ .Values.service.cqlPort }}
          - containerPort: {{ .Values.service.internodePort }}
            hostPort: {{ .Values.service.internodePort }}
          - containerPort: {{ .Values.service.sslinternodePort }}
            hostPort: {{ .Values.service.sslinternodePort }}
          - containerPort: {{ .Values.service.jmxPort }}
            hostPort: {{ .Values.service.jmxPort }}
          - containerPort: {{ .Values.service.restPort }}
            hostPort: {{ .Values.service.restPort }}
          - containerPort: {{ .Values.service.prometheusPort }}
            hostPort: {{ .Values.service.prometheusPort }}
          - containerPort: {{ .Values.service.nodeExporterPort }}
            hostPort: {{ .Values.service.nodeExporterPort }}
          - containerPort: {{ .Values.service.thriftPort }}
            hostPort: {{ .Values.service.thriftPort }}
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_SERVICE_NAME
          value: {{ template "scylladb.fullname" . }}
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        args:
          - --seeds 
          - {{ template "scylladb.fullname" . }}-0.{{ template "scylladb.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
          {{- if and (eq .Values.environment.type "GKE") (.Values.environment.public_access) }}
          - --broadcast-rpc-address
          - {{ .Values.command.gcpGetPublicIP | squote }}
          {{- end }}
          {{- if .Values.resources.limits.cpu }}
          - --smp
          - {{ .Values.resources.limits.cpu | quote }}
          {{- end }}
          {{- if .Values.resources.limits.memory }}
          - --memory
          - {{ .Values.resources.limits.memory | trimSuffix "i" | quote }}
          {{- end }}
        lifecycle:
          preStop:
            exec:
              command: ["/usr/bin/nodetool","flush"]
        readinessProbe:
          exec:
            command: ["/bin/sh", "-c", "exec", "/opt/ready-probe.sh"]
          initialDelaySeconds: 15
          timeoutSeconds: 5
        volumeMounts:
          - name: scylla-ready-probe
            mountPath: /opt/ready-probe.sh
          - name: {{ template "scylladb.fullname" . }}-config
            mountPath: /etc/scylla/scylla.yaml
            subPath: scylla.yaml
          {{- if .Values.persistence.size }}
          - name: datadir
            mountPath: /var/lib/scylla
          {{- end }}
      volumes:
        - name: scylla-ready-probe
          configMap:
            name: {{ template "scylladb.fullname" . }}-probe 
        - name: {{ template "scylladb.fullname" . }}-config
          configMap:
            name: {{ template "scylladb.fullname" . }}-config
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes: 
          - {{ .Values.persistence.accessMode | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
        {{- if (eq .Values.environment.type "GKE") }}
        storageClassName: scylla-ssd
        {{- end }}
